# Build configuration for code generation
targets:
  $default:
    builders:
      # Drift database code generation - APENAS OPÇÕES VÁLIDAS
      drift_dev:
        enabled: true
        options:
          store_date_time_values_as_text: true
          skip_verification_code: false
          use_column_name_as_json_key_when_defined_in_moor_file: true
          # Removido: generate_data_classes (não existe)
        generate_for:
          - lib/core/database/**/*.dart

      # Freezed code generation
      freezed:
        enabled: true
        options:
          copy_with: true
          when: true
          map: true
          equal: true
          to_string: true
        generate_for:
          - lib/**/*.dart

      # JSON annotation code generation
      json_serializable:
        enabled: true
        options:
          any_map: false
          checked: true
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: snake
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
        generate_for:
          - lib/**/*.dart

# REMOVIDO: envied_generator (não é um builder reconhecido)
# Ele funciona através de anotações, não precisa de configuração aqui

# Global options simplificadas
global_options:
  json_serializable:
    options:
      field_rename: snake
      checked: true
      create_factory: true
      create_to_json: true

  freezed:
    options:
      copy_with: true
      when: true
      map: true
      equal: true
      to_string: true
