name: frontend
description: "Sistema de Cadastro Unificado - Flutter App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins: # ← ADICIONADO PARA WEB
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.5.1

  # Navigation
  go_router: ^16.0.0

  # Network
  dio: ^5.6.0
  connectivity_plus: ^6.0.5

  # Local Storage - Web Compatible
  drift: ^2.26.0
  drift_flutter: ^0.2.5

  # SQLite APENAS para mobile/desktop (não web)
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24
  
  # Path provider
  path_provider: ^2.1.4
  path: ^1.9.0
 
  # Environment
  envied: ^1.1.1

  # Serialization
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Forms
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.0.0

  # Firebase
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_analytics: ^12.0.0

  # UI/UX
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  introduction_screen: ^3.1.12
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.8

  # Utils
  intl: ^0.20.2
  logger: ^2.4.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.3.2
  device_info_plus: ^11.5.0
  package_info_plus: ^8.0.2

  # Icons & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.13
  freezed: ^3.1.0
  json_serializable: ^6.8.0
  drift_dev: ^2.20.3
  envied_generator: ^1.1.1

  # Linting
  flutter_lints: ^5.0.0

  # Testing
  mocktail: ^1.0.4

# Flutter Launcher Icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#2563EB"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48

# Native Splash Screen
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_logo.png
  color_dark: "#042a49"
  image_dark: assets/images/splash_logo_dark.png
  android_12:
    image: assets/images/splash_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/splash_logo_dark.png
    icon_background_color_dark: "#042a49"
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env

  # Removendo fontes customizadas inexistentes
  # fonts:
  #   - family: CustomIcons
  #     fonts:
  #       - asset: assets/fonts/CustomIcons.ttf
